/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tools;

import DataBase.ConexionMySQL;
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.PrintStream;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author C0nacyt
 */
public class genDocHTML {

    String sSQLQuery, sSQLServer, sSQLService;
    int typeDoc;

    genDocHTML(int typeDoc, String sSQLQuery) {
        //Sobrecarga para tipo de documento 1, Reporte de consultores general
        this.typeDoc = typeDoc;
        this.sSQLQuery = sSQLQuery;
    }

    public void creaArchivoHTML() throws FileNotFoundException {
        String[] registro = new String[12];
        ConexionMySQL mysql = new ConexionMySQL();
        Connection cn = (Connection) mysql.Conectar();

        try {
            Statement st = (Statement) cn.createStatement();
            ResultSet rs = st.executeQuery(sSQLQuery);
            int numeracion = 1;
            while (rs.next()) {
                registro[0] = rs.getString(numeracion);
                registro[1] = rs.getString("name");
                registro[2] = rs.getString("correo");
                registro[3] = rs.getString("edo");
                registro[4] = rs.getString("con");
                registro[5] = rs.getString("proy");
                registro[6] = rs.getString("fechaI");
                registro[7] = rs.getString("fechaF");
                numeracion++;
            }
            FileOutputStream os = new FileOutputStream("reporteConsultoresGeneral.html");
            PrintStream ps = new PrintStream(os);

            ///<<<<------------COLOCAR CODIGO HTML AQUI ----------------->>>>
            ps.println("  <html>  ");
            ps.println("<head>");
            ps.println("<meta http-equiv=Content-Type content='text/html; charset=windows-1252'>");
            ps.println("<meta name=Generator content='Microsoft Word 15 (filtered)'>");
            ps.println("<style>");
            ps.println("<!--");
            ps.println("/* Font Definitions */");
            ps.println("@font-face");
            ps.println("{font-family:Wingdings;");
            ps.println("panose-1:5 0 0 0 0 0 0 0 0 0;}");
            ps.println("@font-face");
            ps.println("{font-family:'Cambria Math';");
            ps.println("panose-1:2 4 5 3 5 4 6 3 2 4;}");
            ps.println("@font-face");
            ps.println("{font-family:Calibri;");
            ps.println("panose-1:2 15 5 2 2 2 4 3 2 4;}");
            ps.println("@font-face");
            ps.println("{font-family:Cambria;");
            ps.println("panose-1:2 4 5 3 5 4 6 3 2 4;}");
            ps.println("@font-face");
            ps.println("{font-family:Tahoma;");
            ps.println("panose-1:2 11 6 4 3 5 4 4 2 4;}");
            ps.println("/* Style Definitions */");
            ps.println("p.MsoNormal, li.MsoNormal, div.MsoNormal");
            ps.println("{margin-top:2.0pt;");
            ps.println("margin-right:0cm;");
            ps.println("margin-bottom:2.0pt;");
            ps.println("margin-left:0cm;");
            ps.println("font-size:10.0pt;");
            ps.println("font-family:'Cambria',serif;");
            ps.println("color:#595959;}");
            ps.println("p.MsoHeader, li.MsoHeader, div.MsoHeader");
            ps.println("{mso-style-link:'Encabezado Car';");
            ps.println("margin-top:2.0pt;");
            ps.println("margin-right:0cm;");
            ps.println("margin-bottom:2.0pt;");
            ps.println("margin-left:0cm;");
            ps.println("text-align:right;");
            ps.println("font-size:10.0pt;");
            ps.println("font-family:'Cambria',serif;");
            ps.println("color:#595959;}");
            ps.println("p.MsoFooter, li.MsoFooter, div.MsoFooter");
            ps.println("{mso-style-link:'Pie de página Car';");
            ps.println("margin-top:2.0pt;");
            ps.println("margin-right:5.05pt;");
            ps.println("margin-bottom:0cm;");
            ps.println("margin-left:0cm;");
            ps.println("margin-bottom:.0001pt;");
            ps.println("border:none;");
            ps.println("padding:0cm;");
            ps.println("font-size:10.0pt;");
            ps.println("font-family:'Cambria',serif;");
            ps.println("color:#595959;}");
            ps.println("p.MsoTitle, li.MsoTitle, div.MsoTitle");
            ps.println("{mso-style-link:'Título Car';");
            ps.println("margin-top:6.0pt;");
            ps.println("margin-right:0cm;");
            ps.println("margin-bottom:6.0pt;");
            ps.println("margin-left:0cm;");
            ps.println("font-size:14.0pt;");
            ps.println("font-family:'Calibri',sans-serif;");
            ps.println("color:white;");
            ps.println("text-transform:uppercase;}");
            ps.println("p.MsoClosing, li.MsoClosing, div.MsoClosing");
            ps.println("{mso-style-link:'Cierre Car';");
            ps.println("margin-top:30.0pt;");
            ps.println("margin-right:0cm;");
            ps.println("margin-bottom:4.0pt;");
            ps.println("margin-left:0cm;");
            ps.println("font-size:10.0pt;");
            ps.println("font-family:'Cambria',serif;");
            ps.println("color:#595959;}");
            ps.println("a:link, span.MsoHyperlink");
            ps.println("{color:#646464;");
            ps.println("text-decoration:underline;}");
            ps.println("a:visited, span.MsoHyperlinkFollowed");
            ps.println("{color:#969696;");
            ps.println("text-decoration:underline;}");
            ps.println("p.MsoAcetate, li.MsoAcetate, div.MsoAcetate");
            ps.println("{mso-style-link:'Texto de globo Car';");
            ps.println("margin:0cm;");
            ps.println("margin-bottom:.0001pt;");
            ps.println("font-size:8.0pt;");
            ps.println("font-family:'Tahoma',sans-serif;");
            ps.println("color:#595959;}");
            ps.println("span.MsoPlaceholderText");
            ps.println("{color:gray;}");
            ps.println("p.MsoNoSpacing, li.MsoNoSpacing, div.MsoNoSpacing");
            ps.println("{mso-style-link:'Sin espaciado Car';");
            ps.println("margin:0cm;");
            ps.println("margin-bottom:.0001pt;");
            ps.println("font-size:10.0pt;");
            ps.println("font-family:'Cambria',serif;");
            ps.println("color:#595959;}");
            ps.println("p.MsoListParagraph, li.MsoListParagraph, div.MsoListParagraph");
            ps.println("{margin-top:2.0pt;");
            ps.println("margin-right:0cm;");
            ps.println("margin-bottom:2.0pt;");
            ps.println("margin-left:36.0pt;");
            ps.println("font-size:10.0pt;");
            ps.println("font-family:'Cambria',serif;");
            ps.println("color:#595959;}");
            ps.println("p.MsoListParagraphCxSpFirst, li.MsoListParagraphCxSpFirst, div.MsoListParagraphCxSpFirst");
            ps.println("{margin-top:2.0pt;");
            ps.println("margin-right:0cm;");
            ps.println("margin-bottom:0cm;");
            ps.println("margin-left:36.0pt;");
            ps.println("margin-bottom:.0001pt;");
            ps.println("font-size:10.0pt;");
            ps.println("font-family:'Cambria',serif;");
            ps.println("color:#595959;}");
            ps.println("p.MsoListParagraphCxSpMiddle, li.MsoListParagraphCxSpMiddle, div.MsoListParagraphCxSpMiddle");
            ps.println("{margin-top:0cm;");
            ps.println("margin-right:0cm;");
            ps.println("margin-bottom:0cm;");
            ps.println("margin-left:36.0pt;");
            ps.println("margin-bottom:.0001pt;");
            ps.println("font-size:10.0pt;");
            ps.println("font-family:'Cambria',serif;");
            ps.println("color:#595959;}");
            ps.println("p.MsoListParagraphCxSpLast, li.MsoListParagraphCxSpLast, div.MsoListParagraphCxSpLast");
            ps.println("{margin-top:0cm;");
            ps.println("margin-right:0cm;");
            ps.println("margin-bottom:2.0pt;");
            ps.println("margin-left:36.0pt;");
            ps.println("font-size:10.0pt;");
            ps.println("font-family:'Cambria',serif;");
            ps.println("color:#595959;}");
            ps.println("p.MsoQuote, li.MsoQuote, div.MsoQuote");
            ps.println("{mso-style-link:'Cita Car';");
            ps.println("margin-top:10.0pt;");
            ps.println("margin-right:43.2pt;");
            ps.println("margin-bottom:8.0pt;");
            ps.println("margin-left:43.2pt;");
            ps.println("text-align:center;");
            ps.println("font-size:10.0pt;");
            ps.println("font-family:'Cambria',serif;");
            ps.println("color:#404040;");
            ps.println("font-style:italic;}");
            ps.println("p.msonormal0, li.msonormal0, div.msonormal0");
            ps.println("{mso-style-name:msonormal;");
            ps.println("margin-right:0cm;");
            ps.println("margin-left:0cm;");
            ps.println("font-size:12.0pt;");
            ps.println("font-family:'Times New Roman',serif;}");
            ps.println("span.EncabezadoCar");
            ps.println("{mso-style-name:'Encabezado Car';");
            ps.println("mso-style-link:Encabezado;}");
            ps.println("span.PiedepginaCar");
            ps.println("{mso-style-name:'Pie de página Car';");
            ps.println("mso-style-link:'Pie de página';}");
            ps.println("span.TtuloCar");
            ps.println("{mso-style-name:'Título Car';");
            ps.println("mso-style-link:Título;");
            ps.println("font-family:'Calibri',sans-serif;");
            ps.println("color:white;");
            ps.println("text-transform:uppercase;}");
            ps.println("span.CierreCar");
            ps.println("{mso-style-name:'Cierre Car';");
            ps.println("mso-style-link:Cierre;}");
            ps.println("span.TextodegloboCar");
            ps.println("{mso-style-name:'Texto de globo Car';");
            ps.println("mso-style-link:'Texto de globo';");
            ps.println("font-family:'Tahoma',sans-serif;}");
            ps.println("span.SinespaciadoCar");
            ps.println("{mso-style-name:'Sin espaciado Car';");
            ps.println("mso-style-link:'Sin espaciado';}");
            ps.println("p.Encabezadodetabla, li.Encabezadodetabla, div.Encabezadodetabla");
            ps.println("{mso-style-name:'Encabezado de tabla';");
            ps.println("margin-top:2.0pt;");
            ps.println("margin-right:0cm;");
            ps.println("margin-bottom:2.0pt;");
            ps.println("margin-left:0cm;");
            ps.println("font-size:10.0pt;");
            ps.println("font-family:'Calibri',sans-serif;");
            ps.println("color:#7E97AD;");
            ps.println("text-transform:uppercase;}");
            ps.println("span.CitaCar");
            ps.println("{mso-style-name:'Cita Car';");
            ps.println("mso-style-link:Cita;");
            ps.println("color:#404040;");
            ps.println("font-style:italic;}");
            ps.println(".MsoChpDefault");
            ps.println("{font-size:10.0pt;");
            ps.println("font-family:'Cambria',serif;");
            ps.println("color:#595959;}");
            ps.println("/* Page Definitions */");
            ps.println("@page WordSection1");
            ps.println("{size:612.0pt 792.0pt;");
            ps.println("margin:136.95pt 53.85pt 53.85pt 53.85pt;}");
            ps.println("div.WordSection1");
            ps.println("{page:WordSection1;}");
            ps.println("/* List Definitions */");
            ps.println("ol");
            ps.println("{margin-bottom:0cm;}");
            ps.println("ul");
            ps.println("{margin-bottom:0cm;}");
            ps.println("-->");
            ps.println("</style>");
            ps.println("");
            ps.println("</head>");
            ps.println("");
            ps.println("<body lang=ES-MX link='#646464' vlink='#969696'>");
            ps.println("");
            ps.println("<div class=WordSection1>");
            ps.println("");
            ps.println("<p class=MsoNormal><span lang=ES-TRAD>&nbsp;</span></p>");
            ps.println("");
            ps.println("<table class=InvoiceTable border=1 cellspacing=0 cellpadding=0 width='100%'");
            ps.println("style='width:100.0%;border-collapse:collapse;border:none'>");
            ps.println("<tr>");
            ps.println("<td width='32%' style='width:32.78%;border:none;border-bottom:solid #D9D9D9 1.0pt;");
            ps.println("padding:0cm 5.4pt 0cm 5.4pt'>");
            ps.println("<p class=MsoNormal style='margin-top:4.0pt;margin-right:0cm;margin-bottom:");
            ps.println("4.0pt;margin-left:0cm'><span style='font-family:'Calibri',sans-serif;");
            ps.println("color:windowtext;text-transform:uppercase'><img width=221 height=70");
            ps.println("id='Imagen 1' src='reporteConsultoresGeneral_archivos/image001.png' alt=bbb></span></p>");
            ps.println("</td>");
            ps.println("<td width='33%' style='width:33.6%;border:none;border-bottom:solid #D9D9D9 1.0pt;");
            ps.println("padding:0cm 5.4pt 0cm 5.4pt'>");
            ps.println("<p class=MsoNormal align=center style='margin-top:4.0pt;margin-right:0cm;");
            ps.println("margin-bottom:4.0pt;margin-left:0cm;text-align:center'><b><span");
            ps.println("style='font-size:12.0pt;font-family:'Calibri',sans-serif;color:#0D0D0D;");
            ps.println("text-transform:uppercase'>Unidad de Tecnología de la Información y");
            ps.println("Comunicaciones</span></b></p>");
            ps.println("</td>");
            ps.println("<td width='33%' style='width:33.6%;border:none;border-bottom:solid #D9D9D9 1.0pt;");
            ps.println("padding:0cm 5.4pt 0cm 5.4pt'>");
            ps.println("<p class=MsoNormal align=right style='margin-top:4.0pt;margin-right:0cm;");
            ps.println("margin-bottom:4.0pt;margin-left:0cm;text-align:right'><span style='font-family:");
            ps.println("'Calibri',sans-serif;color:white;text-transform:uppercase'><img width=228");
            ps.println("height=71 id='Imagen 2' src='reporteConsultoresGeneral_archivos/image002.png'");
            ps.println("alt=aaa></span></p>");
            ps.println("</td>");
            ps.println("</tr>");
            ps.println("</table>");
            ps.println("");
            ps.println("<p class=MsoNormal align=right style='text-align:right'><span lang=ES-TRAD>FECHA:");
            ps.println("[miércoles 13 de julio de 2016 11:13 a. m.]</span></p>");
            ps.println("");
            ps.println("<table class=MsoNormalTable border=0 cellspacing=0 cellpadding=0 width='100%'");
            ps.println("style='width:100.0%;background:#333639;border-collapse:collapse'>");
            ps.println("<tr>");
            ps.println("<td width='50%' style='width:50.0%;padding:0cm 5.4pt 0cm 5.4pt'>");
            ps.println("<p class=MsoTitle><span lang=ES-TRAD style='color:white'>Reeporte de");
            ps.println("consultores</span></p>");
            ps.println("</td>");
            ps.println("<td width='50%' style='width:50.0%;padding:0cm 5.4pt 0cm 5.4pt'>");
            ps.println("<p class=MsoTitle align=right style='text-align:right'><span lang=ES-TRAD>ELABORÓ:");
            ps.println("$_nombre</span></p>");
            ps.println("</td>");
            ps.println("</tr>");
            ps.println("</table>");
            ps.println("");
            ps.println("<p class=MsoNormal><span lang=ES-TRAD>&nbsp;</span></p>");
            ps.println("");
            ps.println("<table class=MsoNormalTable border=0 cellspacing=0 cellpadding=0 width='99%'");
            ps.println("style='width:99.54%;border-collapse:collapse'>");
            ps.println("<tr style='height:13.1pt'>");
            ps.println("<td width='100%' colspan=3 valign=top style='width:100.0%;border:none;");
            ps.println("border-bottom:solid #7E97AD 1.0pt;padding:0cm 5.4pt 0cm 5.4pt;height:13.1pt'>");
            ps.println("<p class=MsoNormal><b><span lang=ES-TRAD style='color:#0D0D0D'>LA INFORMACIÓN");
            ps.println("QUE SE MUESTRA A CONTINUACIÓN PERTENECE A:</span></b></p>");
            ps.println("</td>");
            ps.println("</tr>");
            ps.println("<tr style='height:24.35pt'>");
            ps.println("<td width='29%' valign=top style='width:29.42%;border:none;padding:0cm 5.4pt 0cm 5.4pt;");
            ps.println("height:24.35pt'>");
            ps.println("<p class=MsoNormal><span lang=ES-TRAD>Consultorías: $_NameCons</span></p>");
            ps.println("</td>");
            ps.println("<td width='20%' valign=top style='width:20.5%;border:none;padding:0cm 5.4pt 0cm 5.4pt;");
            ps.println("height:24.35pt'>");
            ps.println("<p class=MsoNormal><span lang=ES-TRAD>Usuarios: ACTIVOS/INACTIVOS</span></p>");
            ps.println("</td>");
            ps.println("<td width='50%' valign=top style='width:50.08%;border:none;padding:0cm 5.4pt 0cm 5.4pt;");
            ps.println("height:24.35pt'>");
            ps.println("<p class=MsoNormal align=right style='text-align:right'><span lang=ES-TRAD>Rango");
            ps.println("de fecha de alta: [del 6 de abril de 2016 al 7 de agosto de 2016]</span></p>");
            ps.println("<p class=MsoNormal align=right style='text-align:right'><span lang=ES-TRAD>Rango");
            ps.println("de fecha de baja: [del 6 de abril de 2016 al 7 de agosto de 2016]</span></p>");
            ps.println("</td>");
            ps.println("</tr>");
            ps.println("</table>");
            ps.println("");
            ps.println("<p class=MsoNormal><span lang=ES-TRAD>&nbsp;</span></p>");
            ps.println("");
            ps.println("<table class=MsoTable15Grid1Light border=1 cellspacing=0 cellpadding=0");
            ps.println("width='100%' style='width:100.0%;border-collapse:collapse;border:none'>");
            ps.println("<tr>");
            ps.println("<td width='2%' style='width:2.54%;border:solid #999999 1.0pt;border-bottom:");
            ps.println("solid #666666 1.5pt;background:#262626;padding:0cm 5.4pt 0cm 5.4pt'>");
            ps.println("<p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;");
            ps.println("text-align:center'><b><span lang=ES-TRAD style='color:white'>NO</span></b></p>");
            ps.println("</td>");
            ps.println("<td width='19%' style='width:19.54%;border-top:solid #999999 1.0pt;");
            ps.println("border-left:none;border-bottom:solid #666666 1.5pt;border-right:solid #999999 1.0pt;");
            ps.println("background:#262626;padding:0cm 5.4pt 0cm 5.4pt'>");
            ps.println("<p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;");
            ps.println("text-align:center'><b><span lang=ES-TRAD style='font-family:'Calibri',sans-serif;");
            ps.println("color:white'>NOMBRE DEL CONSULTOR</span></b></p>");
            ps.println("</td>");
            ps.println("<td width='15%' style='width:15.22%;border-top:solid #999999 1.0pt;");
            ps.println("border-left:none;border-bottom:solid #666666 1.5pt;border-right:solid #999999 1.0pt;");
            ps.println("background:#262626;padding:0cm 5.4pt 0cm 5.4pt'>");
            ps.println("<p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;");
            ps.println("text-align:center'><b><span lang=ES-TRAD style='font-family:'Calibri',sans-serif;");
            ps.println("color:white'>CORREO</span></b></p>");
            ps.println("</td>");
            ps.println("<td width='4%' style='width:4.5%;border-top:solid #999999 1.0pt;border-left:");
            ps.println("none;border-bottom:solid #666666 1.5pt;border-right:solid #999999 1.0pt;");
            ps.println("background:#262626;padding:0cm 5.4pt 0cm 5.4pt'>");
            ps.println("<p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;");
            ps.println("text-align:center'><b><span lang=ES-TRAD style='font-family:'Calibri',sans-serif;");
            ps.println("color:white'>ESTATUS</span></b></p>");
            ps.println("</td>");
            ps.println("<td width='6%' style='width:6.9%;border-top:solid #999999 1.0pt;border-left:");
            ps.println("none;border-bottom:solid #666666 1.5pt;border-right:solid #999999 1.0pt;");
            ps.println("background:#262626;padding:0cm 5.4pt 0cm 5.4pt'>");
            ps.println("<p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;");
            ps.println("text-align:center'><b><span lang=ES-TRAD style='font-family:'Calibri',sans-serif;");
            ps.println("color:white'>PROYECTO</span></b></p>");
            ps.println("</td>");
            ps.println("<td width='8%' style='width:8.98%;border-top:solid #999999 1.0pt;border-left:");
            ps.println("none;border-bottom:solid #666666 1.5pt;border-right:solid #999999 1.0pt;");
            ps.println("background:#262626;padding:0cm 5.4pt 0cm 5.4pt'>");
            ps.println("<p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;");
            ps.println("text-align:center'><b><span lang=ES-TRAD style='font-family:'Calibri',sans-serif;");
            ps.println("color:white'>CONSULTORIA</span></b></p>");
            ps.println("</td>");
            ps.println("<td width='12%' style='width:12.44%;border-top:solid #999999 1.0pt;");
            ps.println("border-left:none;border-bottom:solid #666666 1.5pt;border-right:solid #999999 1.0pt;");
            ps.println("background:#262626;padding:0cm 5.4pt 0cm 5.4pt'>");
            ps.println("<p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;");
            ps.println("text-align:center'><b><span lang=ES-TRAD style='font-family:'Calibri',sans-serif;");
            ps.println("color:white'>SERVICIOS</span></b></p>");
            ps.println("</td>");
            ps.println("<td width='14%' style='width:14.54%;border-top:solid #999999 1.0pt;");
            ps.println("border-left:none;border-bottom:solid #666666 1.5pt;border-right:solid #999999 1.0pt;");
            ps.println("background:#262626;padding:0cm 5.4pt 0cm 5.4pt'>");
            ps.println("<p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;");
            ps.println("text-align:center'><b><span lang=ES-TRAD style='font-family:'Calibri',sans-serif;");
            ps.println("color:white'>FECHA DE INGRESO</span></b></p>");
            ps.println("</td>");
            ps.println("<td width='15%' style='width:15.34%;border-top:solid #999999 1.0pt;");
            ps.println("border-left:none;border-bottom:solid #666666 1.5pt;border-right:solid #999999 1.0pt;");
            ps.println("background:#262626;padding:0cm 5.4pt 0cm 5.4pt'>");
            ps.println("<p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;");
            ps.println("text-align:center'><b><span lang=ES-TRAD style='font-family:'Calibri',sans-serif;");
            ps.println("color:white'>FECHA DE BAJA</span></b></p>");
            ps.println("</td>");
            ps.println("</tr>");
            ps.println("");
            ps.println("<tr>");
            ps.println("<!--COMIENZA EL CICLO DE LLENADO AUTOMATICO-->");
            
            // --------------->   INICIA LA TABLA LA TABLA
            
            ps.println("<td width='2%' valign=top style='width:2.54%;border:solid #999999 1.0pt;");
            ps.println("border-top:none;padding:0cm 5.4pt 0cm 5.4pt'>");
            ps.println("<p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;");
            ps.println("text-align:center'><span lang=ES-TRAD style='font-size:7.0pt;font-family:");
            ps.println("'Calibri',sans-serif;color:windowtext'>111</span></p>");
            ps.println("</td>");
            ps.println("<td width='19%' valign=top style='width:19.54%;border-top:none;border-left:");
            ps.println("none;border-bottom:solid #999999 1.0pt;border-right:solid #999999 1.0pt;");
            ps.println("padding:0cm 5.4pt 0cm 5.4pt'>");
            ps.println("<p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;");
            ps.println("text-align:center'><span lang=ES-TRAD style='font-size:7.0pt;font-family:");
            ps.println("'Calibri',sans-serif;color:windowtext'>NOMBRE_DEL_CONSULTOR</span></p>");
            ps.println("</td>");
            ps.println("<td width='15%' valign=top style='width:15.22%;border-top:none;border-left:");
            ps.println("none;border-bottom:solid #999999 1.0pt;border-right:solid #999999 1.0pt;");
            ps.println("padding:0cm 5.4pt 0cm 5.4pt'>");
            ps.println("<p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;");
            ps.println("text-align:center'><span lang=ES-TRAD style='font-size:7.0pt;font-family:");
            ps.println("'Calibri',sans-serif;color:windowtext'>EJEMPLOCORREO@ALGO.COM</span></p>");
            ps.println("</td>");
            ps.println("<td width='4%' valign=top style='width:4.5%;border-top:none;border-left:none;");
            ps.println("border-bottom:solid #999999 1.0pt;border-right:solid #999999 1.0pt;");
            ps.println("padding:0cm 5.4pt 0cm 5.4pt'>");
            ps.println("<p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;");
            ps.println("text-align:center'><span style='font-size:7.0pt;font-family:'Calibri',sans-serif;");
            ps.println("color:white'><img width=16 height=16 id='Imagen 4'");
            ps.println("src='reporteConsultoresGeneral_archivos/image003.png'></span></p>");
            ps.println("</td>");
            ps.println("<td width='6%' valign=top style='width:6.9%;border-top:none;border-left:none;");
            ps.println("border-bottom:solid #999999 1.0pt;border-right:solid #999999 1.0pt;");
            ps.println("padding:0cm 5.4pt 0cm 5.4pt'>");
            ps.println("<p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;");
            ps.println("text-align:center'><span lang=ES-TRAD style='font-size:7.0pt;font-family:");
            ps.println("'Calibri',sans-serif;color:windowtext'>ABCDF_PROY</span></p>");
            ps.println("</td>");
            ps.println("<td width='8%' valign=top style='width:8.98%;border-top:none;border-left:");
            ps.println("none;border-bottom:solid #999999 1.0pt;border-right:solid #999999 1.0pt;");
            ps.println("padding:0cm 5.4pt 0cm 5.4pt'>");
            ps.println("<p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;");
            ps.println("text-align:center'><span lang=ES-TRAD style='font-size:7.0pt;font-family:");
            ps.println("'Calibri',sans-serif;color:windowtext'>UAQ_UAQ_INFOTEC</span></p>");
            ps.println("</td>");
            ps.println("<td width='12%' valign=top style='width:12.44%;border-top:none;border-left:");
            ps.println("none;border-bottom:solid #999999 1.0pt;border-right:solid #999999 1.0pt;");
            ps.println("padding:0cm 5.4pt 0cm 5.4pt'>");
            ps.println("");
            ps.println("<!--SE VERIFICA LA EXISTENCIA DE SERVICORES O SERVICIOS-->");
            ps.println("<p class=MsoListParagraphCxSpFirst style='margin-top:2.0pt;margin-right:0cm;");
            ps.println("margin-bottom:0cm;margin-left:18.0pt;margin-bottom:.0001pt;text-indent:-18.0pt'><span");
            ps.println("lang=ES-TRAD style='font-size:7.0pt;font-family:Symbol;color:windowtext'>·<span");
            ps.println("style='font:7.0pt 'Times New Roman''>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;");
            ps.println("</span></span><span lang=ES-TRAD style='font-size:7.0pt;font-family:'Calibri',sans-serif;");
            ps.println("color:windowtext'>SERVICIOS</span></p>");
            ps.println("<p class=MsoListParagraphCxSpLast style='margin-top:2.0pt;margin-right:0cm;");
            ps.println("margin-bottom:0cm;margin-left:18.0pt;margin-bottom:.0001pt;text-indent:-18.0pt'><span");
            ps.println("lang=ES-TRAD style='font-size:7.0pt;font-family:Symbol;color:windowtext'>·<span");
            ps.println("style='font:7.0pt 'Times New Roman''>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;");
            ps.println("</span></span><span lang=ES-TRAD style='font-size:7.0pt;font-family:'Calibri',sans-serif;");
            ps.println("color:windowtext'>SERVIDORES</span></p>");
            ps.println("</td>");
            ps.println("<!--SE VERIFICA LA EXISTENCIA DE SERVICORES O SERVICIOS-->");
            ps.println("<td width='14%' valign=top style='width:14.54%;border-top:none;border-left:");
            ps.println("none;border-bottom:solid #999999 1.0pt;border-right:solid #999999 1.0pt;");
            ps.println("padding:0cm 5.4pt 0cm 5.4pt'>");
            ps.println("<p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;");
            ps.println("text-align:center'><span lang=ES-TRAD style='font-size:7.0pt;font-family:");
            ps.println("'Calibri',sans-serif;color:windowtext'>13 DE SEPTIEMBRE DE 2016</span></p>");
            ps.println("</td>");
            ps.println("<td width='15%' valign=top style='width:15.34%;border-top:none;border-left:");
            ps.println("none;border-bottom:solid #999999 1.0pt;border-right:solid #999999 1.0pt;");
            ps.println("padding:0cm 5.4pt 0cm 5.4pt'>");
            ps.println("<p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;");
            ps.println("text-align:center'><span lang=ES-TRAD style='font-size:7.0pt;font-family:");
            ps.println("'Calibri',sans-serif;color:windowtext'>14 DE NOVIEMBRE DE 2016</span></p>");
            ps.println("</td>");
            ps.println("<!--TERMINA EL CICLO DE LLENADO AUTOMATICO-->");
            
            // --------------->   TERMINA LA TABLA
            ps.println(" ");

            ps.println("</table>");
            ps.println("");
            ps.println("<p class=MsoQuote><span lang=ES-TRAD style='font-size:4.0pt;font-family:'Arial',sans-serif;");
            ps.println("color:white;font-style:normal'>&nbsp;</span></p>");
            ps.println("");
            ps.println("<p class=MsoQuote><span lang=ES-TRAD style='font-size:5.0pt;color:white;");
            ps.println("font-style:normal'>Reporte generado por SISDI (Sistema Integral de la");
            ps.println("Subdirección de Desarrollo e Innovación) Ver 1.2 © 2016 phCrat Derechos");
            ps.println("Reservados</span></p>");
            ps.println("");
            ps.println("</div>");
            ps.println("");
            ps.println("</body>");
            ps.println("");
            ps.println("</html>");
            ps.println("");

            ///<<<<------------COLOCAR CODIGO HTML AQUI ----------------->>>>
            ps.println("     <html><head>");

            
            
            
        } catch (SQLException ex) {
        }
    }
}
